# Generated by Django 4.0.5 on 2022-06-14 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nursering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entreprise', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teleacteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en_cours', models.BooleanField()),
                ('code_campagne', models.CharField(max_length=50)),
                ('code_kami', models.CharField(max_length=50)),
                ('nb_jour', models.IntegerField()),
                ('prix', models.FloatField()),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('chef_projet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
