# Generated by Django 4.0.5 on 2022-06-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='nb_jour',
            new_name='nb_jour_realise',
        ),
        migrations.AddField(
            model_name='project',
            name='nb_jour_total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
