# Generated by Django 4.0.5 on 2022-06-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_project_teleacteurs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_debut',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
